#
## Makefile for ALSA WMT
#
#
obj-$(CONFIG_SND_WMT_AC97) += snd-wmt-alsa-ac97.o
snd-wmt-alsa-ac97-objs := wmt-alsa-ac97.o wmt-alsa-1613-mixer.o  wmt-alsa-1613.o

obj-$(CONFIG_SND_WMT_I2S) += snd-wmt-alsa-i2s.o
snd-wmt-alsa-i2s-objs := wmt-alsa-8328.o wmt-8328-mixer.o es8328.o

#obj-$(CONFIG_SND_WMT_I2S_VT1602) += wmt-alsa-i2s.o wmt-alsa-1602.o wmt-1602-mixer.o vt1602.o
#obj-$(CONFIG_SND_WMT_I2S_ES8328) += wmt-alsa-8328.o wmt-8328-mixer.o es8328.o
