/* Product ID: 8510 / Project ID: 3426 */

#ifndef WM8510_VPP_REG_H
#define WM8510_VPP_REG_H

#define WM8510_VPP_BASE				VPP_BASE_ADDR

#define REG_VPP_INTSTS				(WM8510_VPP_BASE+0x04)
#define REG_VPP_INTEN				(WM8510_VPP_BASE+0x08)
#define REG_VPP_WATCH_SEL			(WM8510_VPP_BASE+0x0c)
#define REG_VPP_SWRST1_SEL			(WM8510_VPP_BASE+0x10)
#define REG_VPP_SWRST2_SEL			(WM8510_VPP_BASE+0x14)

//REG_VPP_INTSTS,0x04
#define VPP_SCL_INTSTS_VBIE			REG_VPP_INTSTS,BIT18,18
#define VPP_SCL_INTSTS_VBIS			REG_VPP_INTSTS,BIT17,17
#define VPP_SCL_INTSTS_PVBI			REG_VPP_INTSTS,BIT16,16
#define VPP_SCL_INTSTS				REG_VPP_INTSTS, 0x70000, 16
#define VPP_GOVRH_INTSTS_VBIE		REG_VPP_INTSTS,BIT10,10
#define VPP_GOVRH_INTSTS_VBIS		REG_VPP_INTSTS,BIT9,9
#define VPP_GOVRH_INTSTS_PVBI		REG_VPP_INTSTS,BIT8,8
#define VPP_GOVRH_INTSTS			REG_VPP_INTSTS, 0x700, 8
#define VPP_GOVW_INTSTS_VBIE		REG_VPP_INTSTS,BIT2,2
#define VPP_GOVW_INTSTS_VBIS		REG_VPP_INTSTS,BIT1,1
#define VPP_GOVW_INTSTS_PVBI		REG_VPP_INTSTS,BIT0,0
#define VPP_GOVW_INTSTS				REG_VPP_INTSTS, 0x07, 0

//REG_VPP_INTEN,0x08
#define VPP_SCL_INTEN_VBIE			REG_VPP_INTEN,BIT18,18
#define VPP_SCL_INTEN_VBIS			REG_VPP_INTEN,BIT17,17
#define VPP_SCL_INTEN_PVBI			REG_VPP_INTEN,BIT16,16
#define VPP_SCL_INTEN				REG_VPP_INTEN, 0x70000, 16
#define VPP_GOVRH_INTEN_VBIE		REG_VPP_INTEN,BIT10,10
#define VPP_GOVRH_INTEN_VBIS		REG_VPP_INTEN,BIT9,9
#define VPP_GOVRH_INTEN_PVBI		REG_VPP_INTEN,BIT8,8
#define VPP_GOVRH_INTEN				REG_VPP_INTEN, 0x700, 8
#define VPP_GOVW_INTEN_VBIE			REG_VPP_INTEN,BIT2,2
#define VPP_GOVW_INTEN_VBIS			REG_VPP_INTEN,BIT1,1
#define VPP_GOVW_INTEN_PVBI			REG_VPP_INTEN,BIT0,0
#define VPP_GOVW_INTEN				REG_VPP_INTEN, 0x7, 0

//REG_VPP_WATCH_SEL,0x0c
#define VPP_WATCH_SEL				REG_VPP_WATCH_SEL, 0x1F, 0

//REG_VPP_SWRST1_SEL,0x10
#define VPP_GE_RST					REG_VPP_SWRST1_SEL,BIT16,16
#define VPP_VID_RST					REG_VPP_SWRST1_SEL,BIT8,8
#define VPP_SCL_RST					REG_VPP_SWRST1_SEL,BIT0,0

//REG_VPP_SWRST2_SEL,0x14
#define VPP_GOVWH_RST				REG_VPP_SWRST2_SEL,BIT16,16
#define VPP_DVO_RST					REG_VPP_SWRST2_SEL,BIT8,8
#define VPP_GOVRH_RST				REG_VPP_SWRST2_SEL,BIT0,0

#endif				/* WM8510_VPP_REG_H */
