/* Product ID: 8510 / Project ID: 3426 */

#ifndef WM8510_GOVM_REG_H
#define WM8510_GOVM_REG_H

#define REG_GOVM_TV_MOD				(GOVM_BASE_ADDR+0x00)
#define REG_GOVM_BNK				(GOVM_BASE_ADDR+0x04)
#define REG_GOVM_GE_STS				(GOVM_BASE_ADDR+0x08)
#define REG_GOVM_VPU_STS			(GOVM_BASE_ADDR+0x0c)
#define REG_GOVM_DISP_CR			(GOVM_BASE_ADDR+0x1c)
#define REG_GOVM_VPU_X_CR			(GOVM_BASE_ADDR+0x20)
#define REG_GOVM_VPU_Y_CR			(GOVM_BASE_ADDR+0x24)
#define REG_GOVM_IND_MOD			(GOVM_BASE_ADDR+0x40)
#define REG_GOVM_IND_APA			(GOVM_BASE_ADDR+0x44)
#define REG_GOVM_COLBAR_EN			(GOVM_BASE_ADDR+0x48)
#define REG_GOVM_INT				(GOVM_BASE_ADDR+0x4c)
#define REG_GOVM_REG_UPDATE			(GOVM_BASE_ADDR+0xc0)
#define REG_GOVM_REG_LEVEL			(GOVM_BASE_ADDR+0xc4)
#define REG_GOVM_COLBAR_MOD			(GOVM_BASE_ADDR+0xd0)
#define REG_GOVM_COLBAR_INV			(GOVM_BASE_ADDR+0xd4)
#define REG_GOVM_GAMMA_MOD			(GOVM_BASE_ADDR+0xe8)
#define REG_GOVM_CLMP_MOD			(GOVM_BASE_ADDR+0xec)

//REG_GOVM_TV_MOD,0x00
#define GOVM_TV_MODE				REG_GOVM_TV_MOD, 0x1, 0

//REG_GOVM_BNK,0x04
#define GOVM_BNK_Y					REG_GOVM_BNK, 0xFF0000,16
#define GOVM_BNK_CB					REG_GOVM_BNK, 0xFF00, 8
#define GOVM_BNK_CR					REG_GOVM_BNK, 0xFF, 0

//REG_GOVM_GE_STS,0x08
#define GOVM_GE_SOURCE				REG_GOVM_GE_STS,BIT0,0

//REG_GOVM_VPU_STS,0x0c
#define GOVM_VPU_SOURCE				REG_GOVM_VPU_STS,BIT0,0

//REG_GOVM_DISP_CR,0x1c
#define GOVM_DISP_Y_CR				REG_GOVM_DISP_CR, 0x7FF0000, 16
#define GOVM_DISP_X_CR				REG_GOVM_DISP_CR, 0x7FF, 0

//REG_GOVM_VPU_X_CR,0x20
#define GOVM_VPU_X_END_CR			REG_GOVM_VPU_X_CR, 0x7FF0000, 16
#define GOVM_VPU_X_STA_CR			REG_GOVM_VPU_X_CR, 0x7FF, 0

//REG_GOVM_VPU_Y_CR,0x24
#define GOVM_VPU_Y_END_CR			REG_GOVM_VPU_Y_CR, 0x7FF0000, 16
#define GOVM_VPU_Y_STA_CR			REG_GOVM_VPU_Y_CR, 0x7FF, 0

//REG_GOVM_IND_MOD,0x40
#define GOVM_IND_MODE				REG_GOVM_IND_MOD,BIT8,8
#define GOVM_IND_MODE_ENABLE		REG_GOVM_IND_MOD,BIT0,0

//REG_GOVM_IND_APA,0x44
#define GOVM_IND_ALPHA_B			REG_GOVM_IND_APA, 0x1FF0000, 16
#define GOVM_IND_ALPHA_A			REG_GOVM_IND_APA, 0x1FF, 0

//REG_GOVM_COLBAR_EN,0x48
#define GOVM_COLBAR_ENABLE			REG_GOVM_COLBAR_EN,BIT0,0

//REG_GOVM_INT,0x4c
#define GOVM_INTSTS_VPU_READY		REG_GOVM_INT,BIT19,19
#define GOVM_INTSTS_GE_READY		REG_GOVM_INT,BIT17,17
#define GOVM_INT_ENABLE				REG_GOVM_INT,BIT8,8
#define GOVM_INTSTS_GOVM_STATUS		REG_GOVM_INT,BIT0,0

//REG_GOVM_UPDATE,0xc0
#define GOVM_REG_UPDATE				REG_GOVM_REG_UPDATE,BIT0,0

//REG_GOVM_LEVEL_SEL,0xc4
#define GOVM_REG_LEVEL				REG_GOVM_REG_LEVEL,BIT0,0

//REG_GOVM_COLBAR_MOD,0xd0
#define GOVM_COLBAR_MODE			REG_GOVM_COLBAR_MOD, BIT0, 0

//REG_GOVM_COLBAR_INV,0xd4
#define GOVM_COLBAR_INVERSION		REG_GOVM_COLBAR_INV, BIT0, 0

//REG_GOVM_GAMMA_MOD,0xe8
#define GOVM_GAMMA_MODE				REG_GOVM_GAMMA_MOD, 0x3, 0

//REG_GOVM_CLMP_MOD,0xec
#define GOVM_CLAMPING_ENABLE		REG_GOVM_CLMP_MOD, BIT0, 0

#endif				/* WM8510_GOVM_REG_H */
